const crossPlatformTests = [
  'tests/unit/utils/windowsCmdShim.test.ts',
  'tests/unit/core/process/ManagedStdioProcess.test.ts',
  'tests/unit/core/collab/CollabProjectsFolder.test.ts',
  'tests/unit/app/collab/local/CollabPathPolicy.test.ts',
  'tests/unit/app/collab/git/CollabGitOriginPolicy.test.ts',
  'tests/unit/app/collab/git/CollabGitTreePolicy.test.ts',
  'tests/unit/app/collab/git/GitCommandRunner.test.ts',
  'tests/unit/app/collab/git/GitCommandRunner.windows.test.ts',
  'tests/unit/app/collab/git/GitRepositoryService.test.ts',
  'tests/unit/app/collab/git/GitRuntimeResolver.test.ts',
  'tests/unit/app/collab/git/collabGitRefs.test.ts',
  'tests/unit/app/collab/lan/LanTlsIdentity.test.ts',
  'tests/unit/app/collab/remote-authority/CloudAuthorityAdapter.test.ts',
  'tests/unit/app/collab/remote-authority/CloudAuthorityUrls.test.ts',
  'tests/unit/app/collab/publish/NativeGitPublicationCandidateRepository.test.ts',
  'tests/unit/app/collab/publish/CollabPublicationService.test.ts',
  'tests/unit/app/collab/publish/NativeGitPublishRepository.test.ts',
  'tests/unit/app/collab/review/NativeGitReviewRepository.test.ts',
  'tests/unit/app/collab/review/NativeGitWorkingTreeReviewRepository.test.ts',
  'tests/integration/app/collab/CollabFilesystemBoundary.test.ts',
  'tests/integration/app/collab/CollabFeatureService.test.ts',
  'tests/integration/app/collab/conflicts/ConflictScratchGitRepository.test.ts',
  'tests/integration/app/collab/git/GitRepositoryService.test.ts',
  'tests/integration/app/collab/git/GitRuntimeResolver.test.ts',
  'tests/integration/app/collab/lan/GitHttpBackendProxy.test.ts',
  'tests/integration/app/collab/lan/git/GitHttpRoute.test.ts',
  'tests/integration/app/collab/lan/git/GitReceiveHookPolicy.test.ts',
  'tests/integration/app/collab/join/JoinProjectCoordinator.test.ts',
  'tests/integration/app/collab/join/JoinProjectLanIntegration.test.ts',
  'tests/integration/app/collab/project/CloudProjectEntryCoordinator.test.ts',
  'tests/integration/app/collab/project/CloudProjectEntryCoordinator.location.test.ts',
  'tests/integration/app/collab/project/CloudProjectEntryCoordinator.recovery.test.ts',
  'tests/integration/app/collab/remote-authority/CloudProjectCredentialStore.test.ts',
  'tests/integration/app/collab/reconciliation/NativeGitAcceptedStateIntegrator.test.ts',
  'tests/integration/app/collab/publish/NativeGitPublicationCandidateRepository.test.ts',
  'tests/integration/app/collab/review/NativeGitReviewRepository.test.ts',
];

const scriptTests = [
  'scripts/check-architecture-boundaries.test.mjs',
  'scripts/check-eslint-config.test.mjs',
  'scripts/check-open-handles.test.mjs',
  'scripts/check-release-version.test.mjs',
  'scripts/check-stylelint-config.test.mjs',
  'scripts/summarize-jest-results.test.mjs',
  'scripts/ciTestSelection.test.mjs',
  'scripts/run-tests.test.mjs',
];

module.exports = { crossPlatformTests, scriptTests };
